name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo 📥
        uses: actions/checkout@v3

      - name: Set up Node 🛠
        uses: actions/setup-node@v3

      - name: Install dependencies 📥
        run: yarn install

      - name: Run tests 🧪
        run: yarn test

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo 📥
        uses: actions/checkout@v3

      - name: Set up Node 🛠
        uses: actions/setup-node@v3

      - name: Semantic Release 🔥
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/git
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
