name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo 📥
        uses: actions/checkout@v3

      - name: Set up Node 🛠
        uses: actions/setup-node@v3

      - name: Install dependencies 📥
        run: yarn install

      - name: Run tests 🧪
        run: yarn test

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo 📥
        uses: actions/checkout@v3

      - name: Set up Node 🛠
        uses: actions/setup-node@v3

      - name: Semantic Release 🔥
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/release-notes-generator@10.0.3
            @semantic-release/git@10.0.1
            @semantic-release/github@8.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
